### ISSUE TITLE
What tools do you use to plot Figure 3(f)?

### ISSUE THREAD

**Issue by Zarzard** [wenzhe-li/romi#1]
Hello! I've read your paper and I wonder what tools do you use to plot the model-uncertainty map. 
Thanks!

**Comment by wenzhe-li** [comment]
Hi Zarzard! You can map the output of model uncertainty to the XY-space of the input (which can be extracted from the state), and scale coordinates to the maze background image.

**Comment by Zarzard** [comment]
Get it, thx a lot!
